### ISSUE TITLE
Sending commands to the ARdrone after python 3.5

### ISSUE THREAD

**Issue by mastahdonkey** [afg984/pyardrone#16]
Hi,

I'm currently running on python 3.5.2
When doing the drone.takeoff() command of your example on the frontpage nothing happens.
After a bit of research in the library i saw that the code was sending something like this
b'AT*REF=26\r'
When I would expect
b'AT*REF=26,290718208\r'
in at BASE.py there is a line saying "should use bytes.format, fix this after python3.5 is released"
What exactly do i need to change?
sidenote, when i'm trying to print the self._parameters at _inter_packed_with_comma() it will just print blank
The variable "command" in __init__.py - at is fine. it just gets lost somewhere.

Do you have any idea what to do about this?

**Comment by mastahdonkey** [comment]
This is what i found out at ATCommand in base.py
I made some comments about my findings in the code

        # should use bytes.format, fix this after python3.5 is released
        print("Base.py line 82 ", self) # for takeoff() REF(INPUT=290718208) 
        print("Base.py line 83 ", seq) # Sequentencenumber
        print("base.py line 84 ", type(self).__name__) # REF or COMWDG
        return 'AT*{clsname}={seq}{argl_wc}\r'.format(
            clsname=type(self).__name__, #Becomes REF
            seq=seq, #Sequencenumber
            #argl_wc stays empty
            argl_wc=b''.join(self._iter_packed_with_comma()).decode()
        ).encode()
    def _iter_packed_with_comma(self):
        # self._parameters is empty here
        for param, arg in zip(self._parameters, self):
            print("base.py line 94 ") #It never prints this line
            yield b','
            yield param._pack(arg)

**Comment by afg984** [comment]
Thanks for your detailed error report. It should be solved by abc2e30.

The issue you reported is actually caused by 0e19e89, in which `at.REF` is changed to be a subclass of `at.REF_0_5` (the old interface), making `ATCommand._pack` ignoring its superclass' `_parameters`, which would contain the input flag.

For the `bytes.format` comment, it is just a note about [pep 461](https://www.python.org/dev/peps/pep-0461/) that we could change to code to avoid the redundant `.decode().encode()`.
The behavior of that portion of code should not be affected by the changes in the python 3.5 language.
